apiVersion: v1
kind: Pod
metadata:
  name: dd-py-flask-app
spec:
  containers:
  - name: flask-app
    command:
    - /opt/scripts/flask-app.py
    image: synfinmelab/dd-py-flask-app:v0.1
    imagePullPolicy: IfNotPresent
